### ISSUE TITLE
Addon name?

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-cli-opinionated#19]
Considering whether or not this is the best name for the addon...at the very least, typing it out during installation isn't the most fun.

Other ideas:

`ember-cli-alfred` (thanks @pixelhandler)
`ember-cli-boilerplate`
`ember-cli-butler`
`ember-cli-concierge` (thanks @pixelhandler)
`ember-cli-enhance`
`ember-cli-jumpstart`
`ember-cli-quickstart`

Welcoming other suggestions/thoughts...is there a better name or is this one perfect? I don't know.

**Comment by ioneyed** [comment]
I actually like it as it makes it very clear as to what is going to be enforced upon the user by selecting that it is an opinionated addon. Just my .02c

**Comment by elwayman02** [comment]
Awesome, thanks for the feedback!
