### ISSUE TITLE
Consider ember-paper and/or ember-cli-materialize

### ISSUE THREAD

**Issue by spencer516** [elwayman02/ember-cli-opinionated#2]
Might be nice to have some UI Sugar built-in by default.

**Comment by elwayman02** [comment]
Anyone have thoughts on a sensible default? I'm leaning toward ember-paper, seems to be a great Ember-first project. My main concern is that being _this_ opinionated might drive people away from the project

**Comment by elwayman02** [comment]
@spencer516 ember-paper has been added to the Q&A now! :)
