### ISSUE TITLE
Include ember-try?

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-cli-opinionated#23]
ember-try is only included in addons right now, but I think it's vital for ember apps as well. @MiguelMadero has made the point that we can test our apps against upcoming versions of ember/ember-data in order to catch issues before we have to upgrade, and I think this should be the default for any Ember app.

**Comment by MiguelMadero** [comment]
Its odd that ember-try is only included for addons. The use case is really different since addons usually need to target multiple versions (eveb old ones) to support different consumers. However the "upgrade" use case is just as important. 

—
