### ISSUE TITLE
Cannot find module 'inflection'

### ISSUE THREAD

**Issue by ioneyed** [elwayman02/ember-cli-opinionated#29]
I installed ember-cli-opinionated for a new project and when I hit the cli to generate a new component I was found with this error:

```
Cannot find module 'inflection'
Error: Cannot find module 'inflection'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/robuchanan/projects/git/rzone/rzone-ui/node_modules/ember-cpm/blueprints/macro/index.js:3:19)
```

So i tried to install ember-inflection and was met with

```
    version: 1.13.13
    Registry returned 404 for GET on https://registry.npmjs.org/ember-inflection
```

```
ember -v
version: 1.13.13
node: 4.2.2
npm: 2.14.10
os: darwin x64
```

**Comment by elwayman02** [comment]
@ioneyed this looks like an issue with ember-cpm, can you open one in that project? It's not trying to load a package called `ember-inflection`, check the stacktrace. It looks like you need to `npm install inflection`, though I'm not sure why you didn't already have it.

https://github.com/cibernox/ember-cpm/blob/9da4a1f8f2f22a1aa445d48e4c0f4a1c679df801/blueprints/macro/index.js
