### ISSUE TITLE
Q&A for Dependency Options?

### ISSUE THREAD

**Issue by spencer516** [elwayman02/ember-cli-opinionated#3]
Perhaps, when running `ember g ember-cli-opinionated`, some options could be presented so the user has some choice.

**Comment by elwayman02** [comment]
:+1: fantastic idea

**Comment by elwayman02** [comment]
This could solve my concern in #2 as well

**Comment by elwayman02** [comment]
Another counter-option is to let the blueprint take option flags, but I think this idea has more pizzazz to it.

**Comment by elwayman02** [comment]
Added! Thanks @spencer516 for the idea!
