### ISSUE TITLE
Include Liquid-fire?

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-cli-opinionated#7]
Great addon that is core to the Ember process now, but it's somewhat difficult to get started with and is definitely not for beginner developers. I'm thinking if we include it at all, maybe part of the questionnaire?

**Comment by acorncom** [comment]
:+1: on making this at least optional.  In the long-run, I believe docs about animations with Liquid-Fire are going to be integrated right into the main guides for Ember, so having it be used here would be great ...

**Comment by elwayman02** [comment]
Yea, that's why I considered it in the first place. I'm hoping the docs improve significantly though, so that setup/usage is easier.

**Comment by elwayman02** [comment]
@acorncom I added liquid-fire as part of the Q&A
